- name: Kirim Perintah Deploy ke EC2
      env:
        HOST: ${{ secrets.EC2_PUBLIC_IP }}
        USER: ec2-user
      run: |
        # Menambahkan -i ~/.ssh/id_rsa agar SSH tahu persis file kunci mana yang harus dipakai
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no $USER@$HOST "docker stop web-app-container || true && docker rm web-app-container || true && docker pull alka31/web-app-lks:latest && docker run -d --name web-app-container -p 80:3000 alka31/web-app-lks:latest" 